.PHONY: clean All

All:
	@echo "----------Building project:[ SpaceFleet - Debug ]----------"
	@cd "SpaceFleet" && "$(MAKE)" -f  "SpaceFleet.mk"
clean:
	@echo "----------Cleaning project:[ SpaceFleet - Debug ]----------"
	@cd "SpaceFleet" && "$(MAKE)" -f  "SpaceFleet.mk" clean
